version: "3.8"

services:
    mongodb: 
        image: mongo:7.0-rc
        container_name: mongodb
        restart: unless-stopped
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - ./database/db:/data/db
            - ./database/dev.archive:/Databases/dev.archive
            - ./database/production:/Databases/production

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: unless-stopped
        links:
            - mongodb
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongodb:27017/?authSource=admin
            - ME_CONFIG_BASICAUTH_USERNAME=mexpress
            - ME_CONFIG_BASICAUTH_PASSWORD=mexpress