FROM python:3.11.4-bookworm
RUN apt update && apt upgrade -y

WORKDIR /backend
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
EXPOSE 5000
CMD ["waitress-serve", "--host", "0.0.0.0", "--port", "5000", "--call", "app:create_app"]
